#!/bin/bash
#
# AIRE files data import
#
#
. /usr/share/glxc/import.init.bash || exit 2

[ -z "$GLXC_DATA_PATH" ] && nef_fatal "missing variable: GLXC_DATA_PATH"
[ -z "$GLXC_AIRE_INSTANCE" ] && nef_fatal "missing variable: GLXC_AIRE_INSTANCE"

state_ref=$(glxc_state_ref_name aire-data-files)
state_commit=$(git show-ref -s $state_ref)
state_tree=
if [ -n "$state_commit" ]; then
    state_tree="$(git ls-tree $state_ref $GLXC_DATA_PATH)"
fi

present_tree="$(git ls-tree $glxc_new_commit $GLXC_DATA_PATH)"

if [ "$state_tree" != "$present_tree" ]; then

    instance_dir=$(eval "$(aire-manager env $GLXC_AIRE_INSTANCE)" && echo $APP_AIRE_INSTANCE_DIR)
    if [ ! -d "$instance_dir" ]; then
        aire-manager install $GLXC_AIRE_INSTANCE 2>&1 | nef_log_pipe "aire install:" \
            || nef_fatal "instance '$GLXC_AIRE_INSTANCE' could not be installed"
    fi

    cd $instance_dir/app
    rm -rf data/
    nef_log "changes detected for path: $GLXC_DATA_PATH"
    nef_log "(re-)importing files into $PWD/data/..."
    git archive $glxc_new_commit $GLXC_DATA_PATH | tar x
    mv $GLXC_DATA_PATH data
    git update-ref -m "import AIRE data from $glxc_new_commit" $state_ref $glxc_new_commit
else
    nef_log "no change for path: $GLXC_DATA_PATH"
fi
