#!/bin/bash
#
# AIRE files data import
#
#
. /usr/share/gitted/import.init.bash || exit 2

[ -z "$GITTED_DATA_PATH" ] && nef_fatal "missing variable: GITTED_DATA_PATH"
[ -z "$GITTED_AIRE_INSTANCE" ] && nef_fatal "missing variable: GITTED_AIRE_INSTANCE"

state_ref=$(gitted_state_ref_name aire-data-files)
state_commit=$(git show-ref -s $state_ref)
state_tree=
if [ -n "$state_commit" ]; then
    state_tree="$(git ls-tree $state_ref $GITTED_DATA_PATH)"
fi

present_tree="$(git ls-tree $gitted_new_commit $GITTED_DATA_PATH)"

if [ "$state_tree" != "$present_tree" ]; then

    instance_dir=$(eval "$(aire-manager env $GITTED_AIRE_INSTANCE)" && echo $APP_AIRE_INSTANCE_DIR)
    if [ ! -d "$instance_dir" ]; then
        aire-manager install $GITTED_AIRE_INSTANCE 2>&1 | nef_log_pipe "aire install:" \
            || nef_fatal "instance '$GITTED_AIRE_INSTANCE' could not be installed"
    fi

    cd $instance_dir/app
    rm -rf data/
    nef_log "changes detected for path: $GITTED_DATA_PATH"
    nef_log "(re-)importing files into $PWD/data/..."
    git archive $gitted_new_commit $GITTED_DATA_PATH | tar x
    mv $GITTED_DATA_PATH data
    git update-ref -m "import AIRE data from $gitted_new_commit" $state_ref $gitted_new_commit
else
    nef_log "No change for path: $GITTED_DATA_PATH"
fi
